name: umccrise

channels:
  - vladsaveliev
  - bioconda
  - conda-forge
  - defaults
  - anaconda

dependencies:
  - python>=3.6
  - bcftools
  - bedtools
  - samtools
  - vcfanno
  - vcflib  # for VCF normalisation
  - pythonpy
  - click
  - cyvcf2
  - numpy
  - pandas
  - curl>=7.59  # to make sure libcurl.4.dylib>=10.0.0 is installed
  - snakemake>=5.1.4vlad
  - nose
  - pip:
    - "--editable=git+https://github.com/umccr/python_utils#egg=python_utils"
    - "--editable=git+https://github.com/umccr/vcf_stuff#egg=vcf_stuff"
    - "--editable=git+https://github.com/vladsaveliev/NGS_Utils#egg=ngs_utils"
  #
  # Umccrise-specific
  - natsort  # for bcbio.py in ngs_utils
  # - pybedtools  # for ref data generation
  # - sambamba  # for test data generation
  # - tabix     # for test data generation
  - goleft
  - awscli
  - pyasn1 # for awscli - for some reason doesn't install automatically on macos
  - cnvkit
  - multiqc
  - networkx   # for snakemake report
  - pygraphviz # for snakemake report
  # R libraries
  - pandoc<2  # r-rmarkdown 1.6 doesn't support pandoc 2, and a more recent r-rmarkdown is not available on conda
  - r
  - r-rmarkdown
  - r-ggplot2
  - r-tidyr
  - r-dt
  - bioconductor-delayedarray
  - bioconductor-summarizedexperiment>=1.8
  - bioconductor-mutationalpatterns
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-txdb.hsapiens.ucsc.hg38.knowngene
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - bioconductor-omiccircos  # for peter's circos rock
  - r-vcfr
  - r-devtools
  - r-readr
  - r-stringr
  - r-htmlwidgets>=1.0  # dependency requirement for DT (by default, 0.9 is getting installed)
