---
# Based on the instructions at http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html

- name: Make sure vital python packages are installed beforehand
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
      - docker

- name: Set route_localnet
  sysctl:
    name: net.ipv4.conf.all.route_localnet
    value: 1
    sysctl_set: yes

- name: Setup port forwarding from 80 to 51679 for metadata (1)
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: 169.254.170.2
    destination_port: 80
    jump: DNAT
    to_destination: 127.0.0.1:51679
    #to_ports: 51679

- name: Setup port forwarding from 80 to 51679 for metadata (2)
  iptables:
    table: nat
    chain: OUTPUT
    destination: 169.254.170.2
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: REDIRECT
    to_ports: 51679

- name: create ecs environment file
  template:
    src=ecs.j2
    dest=/etc/default/ecs
    owner=root
    group=root
    mode=0644

# # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/example_user_data_scripts.html
# - name: create systemd docker service for ecs-agent
#   template:
#     src=docker-container@ecs-agent.service.j2
#     dest=/etc/systemd/system/docker-container@ecs-agent.service
#     owner=root
#     group=root
#     mode=0644

# - name: enable ecs-agent systemd service
#   systemd:
#     name: docker-container@ecs-agent
#     enabled: yes

- name: Configure and run the ecs-agent container
  docker_container:
    name: ecs-agent
    image: amazon/amazon-ecs-agent:latest
    state: started
    restart_policy: always
    detach: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/ecs/:/log
      - /var/lib/ecs/data:/data
    env_file: /etc/default/ecs
    privileged: yes # otherwise we get: [WARN] Disabling TaskCPUMemLimit because agent /sys/fs/cgroup/systemd/ecs: read-only file system

# https://docs.aws.amazon.com/batch/latest/userguide/create-batch-ami.html
- name: Remove the persistent data checkpoint file from ecs-agent
  file:
    state: absent
    path: "/var/lib/ecs/data/ecs_agent_data.json"